default: &default
  adapter: "async"

development:
  <<: *default
  channel_prefix: "hello_development"

test:
  <<: *default
  adapter: "test"

production:
  <<: *default
  channel_prefix: "hello_production"
